<?php
declare(strict_types=1);

$A = '/assets/img/';
$brochure = 'https://drive.google.com/file/d/1ObbqqmENMGtRyrQQIbtI8uGv4Qq_6arj/view';
$apply = '#enquire';

return [
    'junior-college-for-mpc' => [
        'title' => 'MPC with IIT-JEE',
        'seo' => [
            'seo_title' => 'Best Junior College for MPC in Hyderabad | VR Junior College',
            'meta_description' => 'Leading MPC junior college in Hyderabad. VRiiT prepares students for IPE, IIT-JEE and EAMCET with personal guidance and pathways beyond a single exam.',
        ],
        'sections' => [
            ['campaign_hero', [
                'variant' => 'mpc',
                'kicker' => 'VRiiT · MPC with IIT-JEE',
                'heading' => 'Leading MPC junior college in Hyderabad',
                'lead' => 'A 2-year Intermediate programme with integrated IIT-JEE, BITSAT and EAMCET — guided by each student’s strengths, not by one exam.',
                'chips' => "IPE\nIIT-JEE\nBITSAT\nEAMCET\nPersonal guidance",
                'image' => $A . 'gallery/classroom.jpg',
                'figure' => $A . 'programmes/mpc.jpg',
                'crumb' => 'MPC with IIT-JEE',
                'offer_kicker' => 'VRiiT',
                'offer_title' => '2-year Intermediate',
                'offer_text' => 'IPE alongside IIT-JEE, BITSAT and EAMCET — Maths, Physics and Chemistry with a personal study plan.',
                'offer_points' => "Maths, Physics, Chemistry\nPersonalized study plans\nConceptual clarity over rote learning",
                'cta_label' => 'Apply now',
                'cta_url' => $apply,
                'cta2_label' => 'Download brochure',
                'cta2_url' => $brochure,
            ]],
            ['proof', [
                'items' => "Experienced faculty|Guide students through IPE and top entrance exams.\nFocused IIT-JEE coaching|Smart, directed effort over blind cramming.\nPersonal attention|A learning plan around each student’s strengths.\nMany engineering paths|IIT-JEE is one path — not the only one.",
            ]],
            ['highlight', [
                'bg' => 'paper',
                'kicker' => 'Choose the right programme',
                'heading' => '2-year Intermediate, not a JEE long-term course',
                'items' => "2-year Intermediate|MPC with IIT-JEE|IPE plus IIT-JEE, BITSAT and EAMCET — Maths, Physics and Chemistry together.|/assets/img/programmes/mpc.jpg\n1-year Long Term|NEET only at VR|VR does not offer a JEE long-term course. One-year long-term coaching at VR is NEET only.|/assets/img/programmes/neet.jpg",
            ]],
            ['split', [
                'kicker' => 'The programme',
                'heading' => 'MPC with IIT-JEE & EAMCET',
                'lede' => 'If you’re aiming for a career in engineering, our MPC integrated program (VRiiT) is a comprehensive 2-year course that prepares students for the Intermediate Public Examination (IPE) alongside competitive entrance exams such as IIT-JEE, BITSAT, and EAMCET. Welcome to VR Junior College — a leading choice for MPC College in Hyderabad. We believe no child is built for one exam: alongside competitive preparation, we guide each student by their strengths toward the many engineering and career paths open to them.',
                'points' => "Personalized|Study plans built around each student’s strengths and learning style.\nConceptual|Clarity with real-world application — understanding over rote learning.\nGuided|Problem-solving, time management, and exam strategy — smart effort, not blind cramming.\nConfidence-building|Support that keeps students focused and motivated, free from unnecessary pressure.",
                'image' => $A . 'gallery/classroom-back.jpg',
                'cta_label' => 'Talk to admissions',
                'cta_url' => $apply,
            ]],
            ['why', [
                'kicker' => 'Why VR',
                'heading' => 'Why VR Junior College for MPC?',
                'cards' => "Experienced Faculty|Dedicated educators who guide students through IPE and top entrance exams — with a personal, student-focused approach at every step.\nFocused IIT-JEE Coaching|Structured, guided preparation that builds real understanding and skill — smart, directed effort over blind cramming.\nPersonal Attention|Every student is unique. We identify individual strengths and build a learning plan around them, so no one is lost in the crowd.\nMultiple Engineering Pathways|Beyond IPE and entrance exams, we open doors to a wide range of engineering and career options — because IIT-JEE is one path, not the only one.",
                'video_image' => $A . 'gallery/hostel-study.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=_3sTInMS-f4',
            ]],
            ['process', [
                'kicker' => 'Coaching philosophy',
                'heading' => 'Conceptual clarity — not blind cramming',
                'lede' => 'We follow a structured teaching method designed to help every student learn with clarity and confidence — guided at each step, not pressured.',
                'steps' => "Concept|Strong fundamentals first.\nPractice|Guided problem-solving.\nTesting|Chapter-wise tests and mocks.\nAnalysis|Personal performance tracking.",
                'note' => 'Regular assignments and worksheets · Chapter-wise tests · Personal performance tracking and feedback. We focus on problem-solving, time management, a smart exam approach, and confidence free from pressure.',
                'bg' => 'navy',
            ]],
            ['careers', [
                'kicker' => 'After MPC',
                'heading' => 'Career opportunities after MPC',
                'lede' => 'MPC opens doors to a wide range of career paths — far beyond a single entrance exam.',
                'bg' => 'white',
                'cards' => "Engineering (B.Tech / BE)|CSE, Mechanical, Civil, EV technology, robotics, and semiconductor engineering.|/assets/img/careers/engineering.jpg\nArtificial Intelligence & Machine Learning|Smart systems, generative AI, and automation across every industry.|/assets/img/careers/ai-ml.jpg\nData Science & Analytics|Turning data into decisions — in-demand in India and worldwide.|/assets/img/careers/data-science.jpg\nCybersecurity & Cloud Computing|Protecting systems and managing cloud infrastructure.|/assets/img/careers/cybersecurity.jpg\nArchitecture & Design|Sustainable, smart buildings — creativity with technical skill.|/assets/img/careers/architecture.jpg\nDefense, aviation & sciences|NDA and defence services, commercial pilot pathways, B.Sc and research.|/assets/img/careers/aviation.jpg",
            ]],
            ['programs', [
                'kicker' => 'Programmes',
                'heading' => 'Explore VR programmes',
                'lede' => 'Two-year Intermediate with integrated coaching, plus a one-year NEET long-term option.',
            ]],
            ['faq', [
                'kicker' => 'FAQs',
                'heading' => 'Questions families ask',
                'items' => "What programs does VR Junior College offer for MPC?|VR offers a 2-year MPC program (VRiiT) covering Maths, Physics, and Chemistry, with integrated preparation for the Intermediate Public Examination (IPE), IIT-JEE, and EAMCET — plus personal mentorship and pathways into a wide range of engineering careers.\nIs this the same as a long-term JEE course?|No. MPC with IIT-JEE is a two-year Intermediate programme with integrated coaching (IPE + competitive exams). VR does not offer a separate JEE long-term course. One-year long-term coaching at VR is NEET only.\nIs VR Junior College a residential college?|Yes. VR offers residential (hostel) facilities as well as a day-scholar option, so families can choose what suits their child. Hostels provide a safe, home-like environment with healthy meals and supervised study.\nDoes VR provide study materials for MPC?|Yes. Students receive structured, well-organized material designed for deep conceptual understanding rather than rote memorization, along with regular worksheets and chapter-wise tests.\nWhat food and mess facilities are available?|VR provides healthy, hygienic, home-style meals across its campuses. A balanced diet is treated as part of student well-being, keeping learners nourished and focused throughout the day.\nWhere is VR Junior College located, and how do I apply for MPC?|VR has campuses across Hyderabad — Miyapur, Hafeezpet, Madhapur, and Bowrampet. MPC admissions are open; families can visit any campus, call +91 89298 28498 or +91 92569 25643, or enquire on this page.",
            ]],
            ['cta_banner', [
                'kicker' => 'Admissions 2026–27',
                'heading' => 'Join the best junior college for MPC in Hyderabad',
                'text' => 'Take the first step towards a successful engineering future.',
                'image' => $A . 'banner/life-class.jpg',
                'cta_label' => 'Apply now',
                'cta_url' => $apply,
                'cta2_label' => 'Book a campus visit',
                'cta2_url' => '/contact-us/',
            ]],
            ['enquire', [
                'kicker' => 'Admissions open',
                'heading' => 'Enquire about MPC with IIT-JEE',
                'lede' => 'Admissions open for MPC. Tell us a little about the student and we’ll help you choose campus, batch and hostel options.',
                'program' => 'MPC — Integrated',
            ]],
        ],
    ],

    'inter-college-for-bipc-in-hyderabad' => [
        'title' => 'BiPC with NEET',
        'seo' => [
            'seo_title' => 'Best Inter College for BiPC in Hyderabad | VR Junior College',
            'meta_description' => 'VR Doctors Academy — 2-year BiPC with integrated IPE and NEET coaching, personal mentoring, and pathways beyond MBBS to BDS, AYUSH and healthcare careers.',
        ],
        'sections' => [
            ['campaign_hero', [
                'variant' => 'bipc',
                'kicker' => 'VR Doctors Academy · BiPC with NEET',
                'heading' => 'Shaping future doctors in Hyderabad',
                'lead' => 'A 2-year BiPC programme that blends IPE with focused NEET coaching — and opens doors beyond MBBS to BDS, AYUSH and healthcare careers.',
                'chips' => "IPE\nNEET\nBotany & Zoology\nPersonal mentoring\nHealthcare pathways",
                'image' => $A . 'gallery/g8.jpg',
                'figure' => $A . 'programmes/bipc.jpg',
                'crumb' => 'BiPC with NEET',
                'offer_kicker' => 'VR Doctors Academy',
                'offer_title' => '2-year Intermediate',
                'offer_text' => 'IPE plus focused NEET preparation — Botany, Zoology, Physics and Chemistry together.',
                'offer_points' => "Botany, Zoology, Physics, Chemistry\nTopic-wise assignments and mocks\nPathways beyond a single exam",
                'cta_label' => 'Apply now',
                'cta_url' => $apply,
                'cta2_label' => 'Download brochure',
                'cta2_url' => $brochure,
            ]],
            ['proof', [
                'items' => "VR Doctors Academy|A dedicated stream for medical and healthcare aspirants.\nIPE + NEET together|Board exams and entrance prep in one structured programme.\nPersonal mentoring|Weak areas tracked and improved one-on-one.\nBeyond MBBS|BDS, AYUSH, nursing and allied healthcare careers.",
            ]],
            ['highlight', [
                'bg' => 'paper',
                'kicker' => 'Choose the right programme',
                'heading' => '2-year Intermediate, or 1-year NEET only?',
                'items' => "2-year Intermediate|BiPC with NEET|IPE plus focused NEET preparation — Botany, Zoology, Physics and Chemistry together.|/assets/img/programmes/bipc.jpg\n1-year Long Term|Separate NEET programme|An 8–10 month NEET-only course for students who have completed Intermediate, including repeaters.|/assets/img/programmes/neet.jpg",
            ]],
            ['split', [
                'kicker' => 'VR Doctors Academy',
                'heading' => 'Where academic guidance meets personal mentoring',
                'lede' => 'If you’re a BiPC student aiming to crack NEET and earn a seat in a top medical college, your journey begins here. VR Junior College (VR Doctors Academy) offers a programme built around clarity and guidance — not blind pressure. Our 2-year BiPC Integrated Program blends Intermediate Public Examination (IPE) preparation with focused NEET coaching. NEET is one path, not the only one — beyond MBBS it opens doors to BDS, AYUSH, nursing, and many healthcare careers.',
                'points' => "Expert faculty|Physics, Chemistry and Biology educators known for simplifying complex concepts.\nConceptual foundation|Core concepts taught thoroughly — genuine understanding over rote memorization.\nGuided practice|Sample papers, previous years’ NEET papers, and regular mock exams.\nPersonalised attention|Weak areas identified through continuous tracking and one-on-one improvement.",
                'image' => $A . 'life/students-1.jpg',
                'cta_label' => 'Talk to admissions',
                'cta_url' => $apply,
            ]],
            ['why', [
                'kicker' => 'Why VR',
                'heading' => 'Why VR Junior College for BiPC?',
                'cards' => "Expert faculty|Physics, Chemistry and Biology educators known for simplifying complex concepts and making learning clear.\nFocused NEET coaching|Exam structure, previous-year papers and regular mocks — familiarity, speed and confidence.\nPersonal mentoring|Weak areas identified through continuous tracking and one-on-one improvement.\nPathways beyond MBBS|BDS, AYUSH, nursing and allied healthcare careers — NEET is one path, not the only one.",
                'video_image' => $A . 'gallery/g5.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=_3sTInMS-f4',
            ]],
            ['process', [
                'kicker' => 'How we teach',
                'heading' => 'A clear path from concept to exam day',
                'lede' => 'Structured NEET preparation with personal mentoring at every step — guided, never pressured.',
                'steps' => "Foundation|Physics, Chemistry and Biology taught with real understanding.\nPractice|Topic-wise assignments and previous-year papers.\nMocks|Full NEET simulations that build speed and calm.\nMentoring|Personal tracking so weak areas become strengths.",
                'note' => 'Well-structured study material covering the full NEET syllabus · Topic-wise assignments · Regular mock tests · One-on-one improvement plans.',
                'bg' => 'navy',
            ]],
            ['careers', [
                'kicker' => 'After BiPC',
                'heading' => 'Career opportunities after BiPC',
                'lede' => 'NEET is one path. BiPC also opens doors across medicine, dentistry, AYUSH and healthcare.',
                'bg' => 'white',
                'cards' => "MBBS|Government and private medical colleges across India, including AIIMS and JIPMER pathways.|/assets/img/careers/mbbs.jpg\nBDS|Dentistry as a focused clinical career with strong demand.|/assets/img/careers/bds.jpg\nAYUSH|Ayurveda, Homeopathy, Unani and related medical systems.|/assets/img/careers/ayush.jpg\nNursing & allied health|Nursing, physiotherapy, radiology and other clinical support careers.|/assets/img/careers/nursing.jpg\nPharmacy & life sciences|B.Pharm, biotechnology, microbiology and research pathways.|/assets/img/careers/pharmacy.jpg\nPublic health & research|Healthcare administration, epidemiology and scientific research.|/assets/img/careers/research.jpg",
            ]],
            ['programs', [
                'kicker' => 'Programmes',
                'heading' => 'Explore VR programmes',
                'lede' => 'Two-year Intermediate with integrated coaching, plus a one-year NEET long-term option.',
            ]],
            ['faq', [
                'kicker' => 'FAQs',
                'heading' => 'BiPC questions families ask',
                'items' => "What programs does VR Junior College offer for BiPC?|VR offers a 2-year BiPC program (VR Doctors Academy) covering Botany, Zoology, Physics and Chemistry, with integrated preparation for IPE and NEET — plus personal mentorship and pathways into a wide range of medical and healthcare careers.\nDoes VR offer long-term NEET programs?|The 2-year BiPC stream includes integrated NEET coaching. Separately, VR offers an 8–10 month NEET long-term course for students who have completed Intermediate, including repeaters.\nIs VR Junior College a residential college?|Yes. VR offers residential (hostel) facilities as well as a day-scholar option. Hostels provide a safe, home-like environment with healthy meals and supervised study.\nDoes VR provide study materials for NEET?|Yes. Students receive structured material covering the full NEET syllabus, built for deep conceptual understanding rather than rote memorization, along with topic-wise assignments and regular mock tests.\nWhat food and mess facilities are available?|VR provides healthy, hygienic, home-style meals across its campuses. A balanced diet is treated as part of student well-being.\nWhere is VR Junior College located, and how do I apply for BiPC?|VR operates from campuses across Hyderabad, with residential and day-scholar options. Reach the admissions team for a campus visit or counselling — call +91 89298 28498 or +91 92569 25643, or enquire on this page.",
            ]],
            ['cta_banner', [
                'kicker' => 'Admissions 2026–27',
                'heading' => 'Start your BiPC journey at VR',
                'text' => 'Quality education, integrated NEET coaching, and a clear path into medicine and healthcare.',
                'image' => $A . 'banner/life-film.jpg',
                'cta_label' => 'Apply now',
                'cta_url' => $apply,
                'cta2_label' => 'Download brochure',
                'cta2_url' => $brochure,
            ]],
            ['enquire', [
                'kicker' => 'Admissions 2026–27',
                'heading' => 'Enquire about BiPC with NEET',
                'lede' => 'A 2-year Intermediate programme with integrated NEET coaching. We’ll help you choose campus, batch and hostel options.',
                'program' => 'BiPC — Integrated',
            ]],
        ],
    ],

    'neet-long-term' => [
        'title' => 'NEET Long Term',
        'seo' => [
            'seo_title' => 'NEET Long Term Coaching in Hyderabad | VR Junior College',
            'meta_description' => '8–10 month NEET long-term training at VR Doctors Academy for Intermediate-completed students and repeaters — personal mentoring, mock tests and residential options.',
        ],
        'sections' => [
            ['campaign_hero', [
                'variant' => 'neet',
                'kicker' => 'VR Doctors Academy · 1-year',
                'heading' => 'NEET long-term coaching in Hyderabad',
                'lead' => 'An 8–10 month intensive programme for students who have completed Intermediate — including repeaters and fresh pass-outs. Competitive exams only.',
                'chips' => "8–10 months\nNEET only\nRepeaters welcome\nMock tests\nResidential option",
                'image' => $A . 'gallery/hostel-study.jpg',
                'figure' => $A . 'programmes/neet.jpg',
                'crumb' => 'NEET Long Term',
                'offer_kicker' => 'Competitive exams only',
                'offer_title' => '1-year Long Term',
                'offer_text' => 'Focused NEET training for Intermediate-completed students. No IPE / Intermediate board in this programme.',
                'offer_points' => "Full NEET syllabus revision\nRegular mock tests\nOne-on-one mentoring",
                'cta_label' => 'Apply now',
                'cta_url' => $apply,
                'cta2_label' => 'Download brochure',
                'cta2_url' => $brochure,
            ]],
            ['proof', [
                'items' => "8–10 months|A dedicated year for NEET — no Intermediate board exams.\nRepeaters welcome|Built for students who have completed Intermediate, including droppers.\nPersonal tracking|Progress is reviewed individually, not as a crowd average.\nResidential option|Hostel, meals and supervised study for an uninterrupted year.",
            ]],
            ['highlight', [
                'bg' => 'paper',
                'kicker' => 'Choose the right programme',
                'heading' => 'NEET long-term is not the 2-year BiPC stream',
                'items' => "1-year Long Term|NEET Long Term|8–10 months of focused NEET training. No IPE / Intermediate board in this programme.|/assets/img/programmes/neet.jpg\n2-year Intermediate|That’s BiPC with NEET|The 2-year VR Doctors Academy stream blends IPE with integrated NEET coaching.|/assets/img/programmes/bipc.jpg",
            ]],
            ['split', [
                'kicker' => 'VR Doctors Academy',
                'heading' => 'NEET long-term training for future doctors',
                'lede' => 'VR Junior College (VR Doctors Academy) is a trusted NEET coaching institute in Hyderabad, committed to supporting every aspiring medical professional. Our NEET long-term training is an 8–10 month intensive program for students who have completed Intermediate — including repeaters and fresh pass-outs — offering a dedicated, guidance-driven journey toward a medical career with clarity and confidence at every step.',
                'points' => "Personal attention|Experienced faculty, dedicated doubt-clearing sessions and one-on-one counselling.\nIndividual tracking|Every student’s progress is tracked so guidance is tailored — not one-size-fits-all.\nFull NEET syllabus|Structured revision, regular mock tests and personal mentoring from fundamentals to exam day.\nResidential option|A caring, home-like hostel environment with healthy meals and supervised study.",
                'image' => $A . 'gallery/g4.jpg',
                'cta_label' => 'Talk to admissions',
                'cta_url' => $apply,
            ]],
            ['why', [
                'kicker' => 'Why VR',
                'heading' => 'Why VR for NEET long-term?',
                'cards' => "NEET-only coaching|Built around each student’s strengths, with a clear roadmap from fundamentals through full NEET readiness.\nDedicated mentoring|A proven track record of results, backed by regular practice and personal guidance.\nCaring residential life|A home-like hostel environment that keeps students supported through their medical entrance journey.\nNo board-exam split|This year is for competitive exams only — distinct from the 2-year BiPC Intermediate programme.",
                'video_image' => $A . 'gallery/g7.jpg',
                'video_url' => 'https://www.youtube.com/watch?v=_3sTInMS-f4',
            ]],
            ['process', [
                'kicker' => 'The year, in four steps',
                'heading' => 'From diagnosis to exam temperament',
                'lede' => 'A focused 8–10 month plan that rebuilds fundamentals, then raises speed, accuracy and calm.',
                'steps' => "Diagnose|Identify gaps from Intermediate and prior NEET attempts.\nRevise|Full syllabus with structured notes and doubt sessions.\nMock|Full-length NEET papers under exam conditions.\nRefine|Personal feedback so every test improves the next one.",
                'note' => 'Dedicated doubt-clearing · Individual counselling · Regular full-length mocks · Hostel and day-scholar options.',
                'bg' => 'navy',
            ]],
            ['careers', [
                'kicker' => 'Who it’s for',
                'heading' => 'Built for Intermediate-completed students',
                'lede' => 'Repeaters and fresh pass-outs who want a dedicated NEET year — not another two years of Intermediate.',
                'bg' => 'white',
                'cards' => "Repeaters / droppers|A structured second attempt with mocks, doubt sessions and personal tracking.|/assets/img/careers/repeaters.jpg\nFresh Intermediate pass-outs|An 8–10 month runway before the next NEET, with no board-exam split.|/assets/img/careers/passouts.jpg\nNEET-only focus|Competitive exams only — this is not the 2-year BiPC Intermediate programme.|/assets/img/careers/neet-focus.jpg\nPersonal mentoring|Weak areas identified and improved one-on-one, not as a crowd average.|/assets/img/careers/mentoring.jpg\nResidential option|Hostel, meals and supervised study for an uninterrupted year.|/assets/img/careers/residential.jpg\nFull syllabus revision|Structured notes, previous papers and full-length mocks through to exam day.|/assets/img/careers/revision.jpg",
            ]],
            ['programs', [
                'kicker' => 'Programmes',
                'heading' => 'Explore VR programmes',
                'lede' => 'Looking for Intermediate with NEET instead? See BiPC with NEET — the 2-year VR Doctors Academy stream.',
            ]],
            ['faq', [
                'kicker' => 'FAQs',
                'heading' => 'NEET long-term questions',
                'items' => "Does VR offer a NEET long-term course for students who have completed Intermediate?|Yes. VR offers an 8–10 month NEET long-term course in Hyderabad for students who have finished Intermediate and want to focus entirely on NEET. It covers the full syllabus with structured revision, regular mock tests and personal mentoring — ideal for repeaters and recent pass-outs.\nIs this the same as BiPC with NEET?|No. BiPC with NEET is a two-year Intermediate programme (IPE + competitive exams). NEET long-term is a one-year course for competitive exams only.\nWhat programs does VR Junior College offer for NEET?|VR offers a 2-year BiPC program (VR Doctors Academy) with integrated NEET preparation, covering Botany, Zoology, Physics and Chemistry — plus this long-term NEET training and guided coaching for repeaters.\nIs VR Junior College a residential college?|Yes. VR offers residential (hostel) facilities alongside a day-scholar option. Hostels provide a safe, home-like environment with healthy meals and supervised study.\nDoes VR provide study materials for NEET?|Yes. Students receive structured material covering the full NEET syllabus, built for deep conceptual understanding rather than rote memorization, along with topic-wise assignments and regular mock tests.\nWhat is the batch size at VR Junior College?|VR keeps batch sizes focused so every student gets individual attention and one-on-one mentoring during their NEET journey.",
            ]],
            ['cta_banner', [
                'kicker' => 'Admissions 2026–27',
                'heading' => 'Start your NEET long-term year',
                'text' => 'A dedicated 8–10 month journey for Intermediate-completed students and repeaters.',
                'image' => $A . 'banner/life-hostel.jpg',
                'cta_label' => 'Apply now',
                'cta_url' => $apply,
                'cta2_label' => 'View BiPC (2-year)',
                'cta2_url' => '/inter-college-for-bipc-in-hyderabad/',
            ]],
            ['enquire', [
                'kicker' => 'Admissions 2026–27',
                'heading' => 'Enquire about NEET Long Term',
                'lede' => 'An 8–10 month NEET-only programme for students who have completed Intermediate. Tell us a little about the student and we’ll guide the next step.',
                'program' => 'NEET Long Term',
            ]],
        ],
    ],
];
